[package]
name = "bullfinch-kernel"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
name = "kernel"
path = "src/lib.rs"

[dependencies]
dtoolkit = { version = "0.3.0", default-features = false }

[features]
smoke-test = []

[[bin]]
name = "kernel"
path = "src/main.rs"
test = false
bench = false
