name: CI

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Install Rust toolchain
        run: rustup show

      - name: Check formatting
        run: nix develop -c just fmt-check

      - name: Run unit tests
        run: nix develop -c just test

      - name: Run Clippy
        run: nix develop -c just lint

      - name: Smoke test
        run: nix develop -c just smoke
