name: CI

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Install Rust toolchain
        run: rustup show

      - name: Run hooks
        run: nix develop --no-write-lock-file -c just hooks

      - name: Run unit tests
        run: nix develop --no-write-lock-file -c just test

  smoke-arm64:
    name: Smoke ARM64
    runs-on: ubuntu-24.04-arm
    needs: checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Install Rust toolchain
        run: rustup show

      - name: Smoke test
        run: nix develop --no-write-lock-file -c just smoke-arm64

  smoke-riscv64:
    name: Smoke RISC-V
    runs-on: ubuntu-24.04-riscv
    needs: checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Install Rust toolchain
        run: rustup show

      - name: Smoke test
        run: nix develop --no-write-lock-file -c just smoke-riscv64
